= CS 241: Sequential Programs
:showtitle:
:page-navtitle: CS 241: Sequential Programs
:page-root: ../
:toc:
:stem:

== May 7th: Intro

=== Bits and Bytes

This course is about making compilers.
We start off bare hardware and build up to a C-like language.
Our hardware is a simulated MIPS machine.

[options="header"]
|===

|Type |Meaning

|Bit
|1 or 0

|Nibble
|4 bits

|Byte
|8 bits

|Word
|Depends on arch size; 32 bits in CS241

|===


=== Number Systems

In decimal, base 10 works like this: stem:[12345 = 1*10^4 + 2*10^3 + 3*10^2 + 4*10^1 + 5*10^0].

In binary, it's the same. stem:[10101 = 1*2^4 + 0*2^3 + 1*2^2 + 0*2^1 + 1*2^0].

To covert a decimal number to binary, you find the largest power of two smaller than it, set that
digit of your new binary number to 1, subtract it from the original number, and repeat until you
reach zero.

How do we encode negative numbers in binary?

"Pick a bit, if it's 1, it's negative, if it's 0, it's positive." That's the intuitive solution,
*sign-magnitude* binary. It's conceptually easy, but it makes a lot of arithmetic a pain in the
ass. It also gives you stem:[+0] and stem:[-0], which is just wasteful.

Which brings us to *two's complement.*

. Interpret the n-bit number as an unsigned int.
. If the first bit is 0, then it's a regular positive binary number.
. Otherwise, subtract stem:[2^n].

[options="header"]
|===

|number |value 

|000 |0
|001 |1
|010 |2
|011 |3
|100 |-4
|101 |-3
|110 |-2
|111 |-1

|===

Benefits:

- Only one zero
- Left bit gives sign
- Addition is clean --- just arithmetic mod stem:[2^n].

To convert a positive number to a negative number in two's complement, flip every bit and add one.

To convert a negative to a positive, you can reverse the process... Or just do it again. It's
equivalent either way, which is cool.


== May 9th

=== Registers

ML uses binary instructions.

Memory comes in tiers:

|===
|CPU registers
|L1, L2, L3 cache
|RAM
|SSD/HDD memory
|===

A CPU has a very limited number of very fast, but  small memory storage locations called 
*registers*. Our MIPS architecture has 32 registers, each holding 32 bits. It's 128 bytes total.

- CPU can only operate on data stored in registers.
- If data is not currently in a register, you have to load it from RAM
- Registers are labelled $1, $2, $3, $4, $5, etc.
- $0 is always 0, changing that breaks things
- $31 is special, $30 is special, $29 is sort of special

5 bits are needed to encode a register address.

MIPS assembly looks like `add $d, $s, $t` -- "Add the values in registers 7 and 8,
and store the result in register 27."
In binary, that looks like `0000 00ss ssst tttt dddd d000 0010 0000`.

Example: `add $7, $8, $27`.
In binary, this works out to `0000 0000 1110 1000 1101 1000 0010 0000`.

.Conventions
****
Make sure to write binary in blocks of four, for legibility.
But normally, for convenience, we use hexadecimal instead of binary.
Denote hex numbers with the prefix `0x`, as in `0x6af2`.
This way, our example instruction from above becomes
`0x00e8d820`. Ain't it nice?
****

=== RAM

RAM is basically just a big array, which is far away from the CPU.
Each cell has an address, 0, 1, 2, ... n-1, for n cells of RAM.
Each 4-byte block of ram is a word.
Words have addresses 0, 4, 8, 12, etc.
These addresses are *word-aligned*.
Data in RAM must be loaded into registers before the CPU can read them.

WARNING: Accessing data in RAM is very slow compared to register access.

There are two operations to read in RAM: load and store.
Load transfers a word from a source address in RAM into a target register.

How loading works:

- Address is stored in Memory Address REgister (MAR)
- Address then goes on the bus to RAM
- Data from that location is returned to the bus and stored in the MDR
- THe contents of the MDR are then moved to the target register

Storing is that but in reverse

=== Executing Code

How does the CPU know which instruction to execute next?
A special register called the Program Counter (PC) stores the memory address of the
next instruction to execute.
The Instruction Register (IR) holds the current instruction.

But a program needs a starting point. By convention, we guarantee that a specific address (like 0)
contains code.

****
A program called a *loader* puts a program into memory and sets the PC to the address of the first
instruction.

CS241 uses mips, twoints, and mips.array taht load programs into memory address 0.

We will talk about other addresses later.
