= CS 251: Computer Architecture
:showtitle:
:page-navtitle: CS 251: Computer Archiecture
:page-root: ../
:toc:
:stem:

== May 7th: Intro

Introduction to the idea of truth tables.

But those are a pain! So we use boolean algebra instead.
Similar to predicate logic, but stem:[xx] instead of stem:[^^]
and stem:[*] instead of stem:[vv].
stem:[not] stays the same. That's about it.

We also use stem:[bar A] for the negation of stem:[A].

Basically:

[options:"header"]
|===
|stem:[X] |stem:[Y] |stem:[Z] |stem:[F] |stem:[G] |stem:[bar G]

|0 |0 |0 |0 |1 |0

|0 |0 |1 |0 |1 |0

|0 |1 |0 |0 |1 |0

|0 |1 |1 |0 |1 |0

|1 |0 |0 |0 |1 |0

|1 |0 |1 |1 |1 |0

|1 |1 |0 |1 |1 |0

|1 |1 |1 |1 |0 |1

|===

Much easier to just represent this as stem:[F = X bar Y Z + X Y bar Z + X Y Z ]
-- the equation defining the truthiness of F.

You can also see X instead of 1 or 0 in a truth table.
This means that the value of that column doesn't affect
the outcome either way.

Using X, we can express a table much more concisely. For instance,

[options:"header"]
|===
|stem:[X] |stem:[Y] |stem:[Z] |stem:[F]

|X |X |1 |1

|X |X |0 |0
|===

is much more concise than it would otherwise be.


== May 9th

The most concise way to talk about hardware components is as a truth
equation in minimal terms.

To get this, you take just the true cases and add them togeter,
a la stem:[bar X Y + XY = F]. Sometimes you can further reduce it
by hand, using boolean algebra rules, as in stem:[bar X Y + XY = Y = F].

Symbols for logic gates:

* AND is a D shape
* OR is a rounded chevron shape, like a triangle with the back pushed in.
* NOT is a triangle with a bubble at the tip)
* NAND and NOR are AND and OR but with tip bubbles respectively


=== Transistors

A transistor is like a switch. It has two inputs and an output; whether or not
the first input is powered determines whether or not power can flow hrought he second
and third inputs.

THere are two types: NMOS and PMOS.

[options="header"]
|===
|Type |Resistence when control input is on |Resistence when control input is off
|NMOS |Low |High
|PMOS |High |Low

PMOS is drawn like NMOS but with a circle on the control input.

TIP: A **N**egative correlation has y high when x is low and x high when y is low,
like an **N**MOS transistor. A **P**ositive correlation is the other way around,
like a **P**MOS transistor. And since positive means _more_, a PMOS transistor
has an _extra_ circle on it.

== May 14th

=== XOR

The XOR gate is like an OR gate, but with a line on the input end, parallel to that
side of the triangle. XNOR is the same with the NOR gate.

=== Decoders and Multiplexers

A *decoder* takes a binary number (encoded in electric signals) and turns on one corresponding
output for each possible number. A decoder with stem:[n] inputs outputs stem:[2^n] outputs,
only one of which is ever on at a time.

A *multiplexer* (mux) with stem:[n] primary inputs has stem:[ceil(log_2 n)] secondary inputs.
The binary pattern in the secondary inputs determines which of the primary inputs is passed
through into the single output.

Both of these can be used to create simpler implementations of complex gates.
The outputs of a decoder for which the gate is on can simply be ORed together;
and in a gate where, for instance, input stem:[X] determines the output when input
stem:[Y] is on, and input stem:[Z] determines the output when input stem:[Y] is off,
a mux can use stem:[Y] to toggle between passing stem:[X] or stem:[Y] through.
