= MATH 239: Combinatorics
:showtitle:
:page-navtitle: MATH 239: Combinatorics
:page-root: ../
:toc:
:stem:

== Intro

The two subjects this course covers are Enumeration and Graph Theory.
We're gonna do 5 weeks of Enumeration, and 7 weeks of Graph Theory.

The typical Enumeration question is "How many elements of a set stem:[S] of
'combinatorical objects' have a given property?" We'll usually answer them by
encoding the properties of stem:[S] into an algebraic expression called the
*generating series* for stem:[S].

For example: How many ways can we choose a dozen donuts if the available
flavours are chocolate, maple, lemon, and plain (and at least 12 are in
stock)?

Answer is the coefficient of stem:[x^12] in stem:[1/((1-x)^4)]

Same question but only 3 chocolate and 5 maple left.

Answer is the coefficient of stem:[x^12] in stem:[((1-x^4)(1-x^6))/((1-x)^4)].

Standard framework for enumeratiton problems: We define a set stem:[S] and a weight
function stem:[omega] that assigns each element stem:[sigma] of stem:[S] a nonnegative integer
stem:[omega(sigma)].

In Q1, stem:[S] is the set of all collections of donuts from the 4 flavours, and
the weight function is stem:[w(sigma) = "the number of donuts in " sigma]. Then we
ask, "how many elements of stem:[S] have a weight of 12?

Usually our set stem:[S] is a *Cartesian product* of a *disjoint union* of Cartesian
products. Recall that for sets stem:[A] and stem:[B], the Cartesian product stem:[AxxB]
is the set stem:[AxxB = {(a, b): a in A, b in B}].

The *union* stem:[AuuB] is stem:[AuuB = {x: x in A or x in B}], and the *intersection*
stem:[AnnB] is stem:[AnnB = {x: x in A and x in B}]. The set stem:[AuuB] is a
*disjoint union* if stem:[AnnB = O/] when stem:[A] and stem:[B] are finite sets, the *size* of stem:[AxxB, AuuB, " etc"] (denoted by stem:[|AuuB|, |AxxB|, " etc"]) is given by
stem:[|AxxB| = |A| |B|] and stem:[|AuuB| = |A| + |B| - |AnnB|].

So if stem:[AuuB] is a *disjoint* union we set stem:[|AuuB| = |A| + |B|].

The kth *Cartesian power* of a set stem:[A] is the set of all ordered k-tuples of elements
of stem:[A].

[stem]
++++
A^k = {(a_1, a_2, ..., a_k): a_i in A " for each " i}
++++

If stem:[A] is a finite set then stem:[|A^k| = |A|^k].

Suppose the donut shop has 3 chocolate, 5 maple, 19 lemon, and 17 plain donuts.
Describe all possible collections of donutes (of any size) as a Cartesian product.

[stem]
++++
{0,1,2,3} xx {0,1,2,3,4,5} xx {0,1,2, ... ,19} xx {0,1,2, ... ,17}
++++

Ok, fix a positive integer stem:[m]. Let stem:[S] be the subset of all subsets of
stem:[{1, 2, ..., m}].
Let the weight function stem:[omega] be defined on stem:[S] by stem:[omega(sigma)=|omega|].

How many elements of stem:[S] have weight stem:[k]? (for any stem:[k])

Answer is stem:[((m), (k))].



== n choose k

The number stem:[B(m, k)] of k-subsets of stem:[{1, 2, ..., m}]
is stem:[(m(m-1)...(m-k+1))/(k!)].

Proof: Let stem:[L] be the set of all ordered k-tuples of distinct elements of
stem:[{1, 2, ..., m}]. Then stem:[|L| = m(m-1)(m-2)...(m-k+1)].

We could also count stem:[|L|] by listing all stem:[B(m, k)] k-subsets of
stem:[{1, 2, ..., m}] and ordering each in all stem:[k!] possible ways.

So stem:[|L| = B(m, k)k!].
We use the notation stem:[((m), (k)) = (m(m-1)...(m-k+1))/(k!)]

[NOTE]
====
This expression is defined for all stem:[K >= 0 in ZZ] and all stem:[m in RR]
(or even all stem:[m in CC]). When stem:[m >= k] is an integer:

- stem:[((m), (k)) = (m!)/((m-k)!k!)]
- stem:[((m), (k)) = ((m), (m-k))]
- stem:[((m), (k)) = 0]
- stem:[0!] is the *empty product*, which is 1. So stem:[((m), (0)) = 1]
====

== Bijections

A *bijection* (or 1-to-1 correspondence) from a set stem:[S] to a set stem:[T] is a functon
stem:[f: S -> T] that is:

- 1-1, which means stem:[f(s_1) = f(s_2) -> s_1 = s_2] (injection)
- onto,  which means stem:[AA t in T; EE s in S; f(s) = t] (surjection)

If stem:[f: S -> T] is a bijection, then stem:[|S| = |T|].

****
There is a bijection stem:[f] from stem:[S =] the set of all subsets of stem:[{1, ..., m}]
to stem:[T = {0, 1}^m] (where exponentiation means repeated Cartesian product). Proof
is not complex.
****

.Lemma
****
If stem:[f: S -> T] has an inverse, then it's a bijection.

Proof: Let stem:[g: T -> S] be the inverse of f.

Check f is 1-1: if stem:[f(s_1) = f(s_2)], then
stem:[g(f(s_1)) = g(f(s_2))], so stem:[s_1 = s_2]. Hence f is 1-1.

Check f is onto: Let stem:[t in T]. Let stem:[s = g(t)]. Then
stem:[f(s) = f(g(t))] = t]. Hence stem:[f] is onto.

Therefore stem:[f] is a bijection. stem:[square].

The converse (that stem:[f] being a bijection makes it have an inverse]
also holds.
****

.Corollary
****
[stem]
++++
sum _k=0 ^m ((m), (k)) = 2^m
++++

We are writing the size of the set of all subsets of stem:[{1, ..., m}] in
two ways.

This is a *combinatorial proof*, where we count the members of a set in two
different ways and get two different expressions of its size, which must then
be equal
****



== Binomial Theorem:

[stem]
++++
AA m in ZZ_(>=0) AA x (1+x)^m = sum _k(k=0) ^m ((m), (k)) x^k

"Proof: " (1+x)^m = (1+x)(1+x)...(1+x) = (x^0 + x^1) (x^0 + x^1) ... (x^0 + x^1)

= x^(0+0+0+...) + x^(1+0+0+...) + ... " ("2^n" terms")
++++

Our bijection from last class, which mapped the subsets of a set with size m to
stem:[{0, 1}^m] applies here, since the exponent terms fit that pattern.

The number of terms in which the exponent adds up to exactly k is the number
of elements of T with exactly k 1s. By our bijection, we know that the number
of k-subsets of stem:[{1, ..., m}]. It's stem:[((m), (k))]. Thus:

[stem]
++++
(1+x)^m = sum _(k=0) ^m ((m), (k)) x^k
++++

.Corollary
****
[stem]
++++
sum _(k=0) ^m ((m), (k)) = (1+1)^m = 2^m
++++
****

This is a great demonstration of the idea of a combinatorical proof.
The idea is to express numbers in terms of the size of a set, which
we describe in two different ways.

Often binomial coefficients are involved.

For instance: give a combinatorial prove that stem:[((n), (k)) = ((n-1), (k)) + ((n-1), (k-1))].

Proof: we take stem:[((n),(k))] as the size of S,
which is the set of all k-subsets of stem:[{1, 2, ..., n}].

We can write stem:[S = S_0uuS_1], where stem:[S_0nnS_1 = O/] where stem:[S_0 =] the
set of all k-subsets of {1, 2, ..., n} that do NOT contain the last element n.
stem:[S_1 = ] those that do.

Then stem:[S_0] is the set of k-subsets of stem:[{1, 2, ..., n-1}]. Therefore
stem:[|S_0| = ((n-1), (k))].

Then there is a bijection from stem:[S_1] to the set of all (k-1)-subsets of
stem:[{1, 2, ..., n-1}] obtained by removing the element n. Thus,
stem:[|S_1| = ((n-1),(k-1))]. Hence:

[stem]
++++
((n),(k)) = |S| = |S_0| + |S_1| = ((n-1),(k)) + ((n-1),(k-1))
++++

Theorem: For stem:[n, k in ZZ_(>=0)], we have
stem:[((n+k),(n)) = sum _(i-0) ^k ((n+i-1),(n-1))].

Proof: Let stem:[S] be the set of of all n-subsets of stem:[{1, 2, ..., n+k}].
Then stem:[|S| = ((n+k),(n))].

Let stem:[S_i] be the set of all n-subsets of stem:[{1, ..., n+k}] whose largest
element is stem:[n+i]. Do this for stem:[0<=i<=k]. Then stem:[S=S_0uuS_1uu...uuS_k] is
a disjoint union. For each i, each element of stem:[S_i] is of the form
stem:[sigma =Auu{n+1}], where A is an (n-1)-subset of stem:[{1, 2, ..., n+i-1}],
since stem:[n+i] is the largest element in stem:[sigma].

Conversely, every (n-1)-subset A of stem:[{1, 2, ..., n+1-1}] together with stem:[n_1]
gives an element of stem:[S_i]. So we get a bijection from stem:[S_i] toi the set of
(n-1)-subsets of stem:[{1, 2, ..., n+i-1}] obtained by removing stem:[n+i].

Hence stem:[|S_i| = ((n+i-1),(n-1))]. Thus,

[stem]
++++
((n_k),(n)) = |S| = sum _(i=0) ^k |S_i| = sum _(i=0) ^k ((n+i-1),(n-1))

square
++++

For a set S, a *weight function* on S is a function stem:[w: S -> ZZ_(>=0)] such that
for each stem:[n in ZZ_(>=0)], the number of elements stem:[sigma in S] with
stem:[w(sigma) = n] is finite.



== Weight functions and indeterminates

A *weight function* on a set stem:[S] is a function stem:[w: S -> ZZ_(>=0)] such that,
for every stem:[n >= 0], stem:[{sigma in S: w(sigma)=n}] is finite.

Let stem:[S] be a set and let stem:[w] be a weight function on stem:[S]. The *generating
series* for stem:[S] with respect to stem:[w], in the indeterminate stem:[x], is

[stem]
++++
Phi_s(x) = sum _(sigma in S) x^(w(sigma)).
++++

We can collect the like terms and write

[stem]
++++
Phi_s(x) = sum _(k>=0} a_k x^k
++++

where stem:[a_k] is the number of elements of stem:[S] of weight stem:[k].

====
Let stem:[S =] the set of all subsets of stem:[{1, 2, ..., m}].
Let stem:[w(sigma) = |sigma|]. Then

[stem]
++++
Phi_s(x) = sum _(k>=0) ((m),(k)) x^k = sum _(k = 0) ^m ((m),(k)) x^k = (1+x)^m
++++
====

====
[stem]
++++
S = ZZ_(>=0)

w(sigma) = sigma

Phi_s(x) = sum_(i>=0) x^i
++++
====

stem:[x] is an *indeterminate*. Don't think of it as something that you substitute
for a number; doing that with a generating series just gets you noise (unless stem:[S]
is finite).

An indeterminate is a symbol that satisfies stem:[x^0 = 1, x^a+x^b = x^(a+b),
(x^a)^b=x^(ab)].

If stem:[S] is infinite, stem:[Phi_s(x)] is an infinite sum. This will be a *formal power series*
(more on that later).

.Theorem
****
Let stem:[S] be a finite set with weight funtion stem:[w] (so stem:[Phi_s(x)] is a polynomial).
Then

. stem:[Phi_s(1) = |S|]
. stem:[Phi_s'(1)] is the total weight of all elements in stem:[S].

Proof:

[stem]
++++
Phi_x(s) = sum _(sigma in S) x^(w(sigma))

Phi_s(1) = sum _(sigma in S) 1^(w(sigma)) = |S|

Phi_s'(x) = sum _(sigma in S) w(sigma) x^(w(sigma)-1)

Phi_s'(1) = sum _(sigma in S) w(sigma)
++++
****

====
stem:[S] is the set consisting of 5 nickels, 12 dimes and 3 quarters. Let stem:[w(sigma)=] the 
value of stem:[sigma], in cents.

[stem]
++++
Phi_s(x) = 5x^5 + 12x^10 + 3x^25

Phi_s'(x) = 25x^4 + 120x^9 + 75x^24

Phi_s(1) = 5 + 12 + 3 = 20

Phi_s'(1) = 25 + 120 + 75 = 220
++++
====

== Formal power series

.Definiton
****
A *formal power series* over the rational numbers in the indeterminate stem:[x] is a formal
expression of the following type:

[stem]
++++
A(x) = sum _(i>=0) a_i x^i, a_i in QQ
++++

You can do several kinds of arithmetic with them.

* Addition: for stem:[A(x) = sum _(i>=0) a_i x^i]l and
stem:[B(x) = sum _(i>=0) b_i x^i] we define
+
[stem]
++++
A(x)+B(x) = sum _(i>=0)(a_i+b_i)x^i
++++
+
Subtraction follows trivially.

* Multiplication generalizes polynomial multiplication:
+
[stem]
++++
A(x)B(x) = sum_(i>=0) (sum _(j=0) ^i a_j b_(i-j))x^i
++++
+
Note that stem:[A(x)B(x) = B(x)A(x)].

* Equality: stem:[A(x) = B(x)] if and only if stem:[a_i=b_i] across all stem:[i>=0].

* Coefficients: stem:[a_i] is called the *coefficient* of stem:[x^i] in stem:[A(x)].
We write stem:[a_i=\[x^i\]A(x)].

* Inverse: We say that stem:[B(x)] is the multiplicative inverse of stem:[A(x)] if
stem:[A(x)B(x) = 1 = 1+0x+0x^2+...].
****


== Inverses of Power Series

An fps stem:[A(x) = sum _(i>=0) b_i x^i] has *inverse* stem:[B(x) = sum _(i>=0) b_i x^i] if 
stem:[A(x)B(x) = 1]. We write stem:[B(x) = A^-1(x)] or stem:[B(x) = 1/(A(x)].

====
[stem]
++++
A(x) = 1+x+x^2+x^3+...

B(x) = 1-x

(1-x)(1+x+x^2+x^3+...)
= 1

:. A^-1(x) = B(x)
++++

We often write stem:[1+x+x^2+x^3+... = 1/(1-x)] or stem:[(1-x)^-1].
====

== Composition (or Substitution) of Formal Power Series

If stem:[B(x)] has a constant coefficient stem:[b_0 = 0], then stem:[A(B(x))] is a fps.

We can write stem:[B(x) = xC(x)] where stem:[C(x) = b_1 + b_2x + b_3x^2 + ...].
Then stem:[A(B(x)) = a_0 + a_1xC(x) + a_2x^2C^2(x) + a_3x^3C^3(x) + ...].
We need to verify that for every stem:[n], the coefficient stem:[\[x^n\]A(B(x))] of
stem:[x^n] is a finite number.

But stem:[\[x^n\]A(B(x)) = \[x^n\](a_0 + a_x xC(x) + ... + a_n x^n C^n(x))].
This is a finite number, since we have a finite sum of products of fps.

Hence stem:[A(B(x))] is an fps.

TIP: Whenever you do anything to a formal power series, you gotta make sure that all
the coefficients are finite. That's the thing that'll throw you off.

.Theorem
****
A fps stem:[A(x)] has an inverse if and only if the constant coefficient stem:[a_0 != 0].
****

Proof: Suppose stem:[C(x)] is the inverse of stem:[A(x)]. Then stem:[A(x)C(x)] = 1.
But the constant coefficient of stem:[A(x)C(x)] is stem:[a_0c_0 = 1]. Hence
stem:[a_0 != 0].

Now suppose stem:[a_0 != 0]. Then we can write stem:[A(x) = a_0(1-xB(x)] where
stem:[B(x) = -a_1/a_0 + a_2/a_0 + a_3/a_0 + a_4/a_0 + a_5/a_0 + ...].

So stem:[1-xB(x)] is stem:[xB(x)] substituted into stem:[1-x], and we know stem:[1-x]
has an inverse stem:[sum_(i>=0} x^i]. Hence we know stem:[1-xB(x)] has an inverse
stem:[sum_(i>=0)(xB(x))^i]. So stem:[A(x)] has an inverse stem:[1/a_0 sum_(i>=0) x^i B^i(x)].

====
Show that if stem:[A(x)] has an inverse, then it's unique.
====

.Theorem
****
Let stem:[m] be a positive integer. Then stem:[(1-x)^m = sum _(k>=0) ((m+k-1),(m-1)) x^k].
****

Proof: By induction on stem:[m]: When stem:[m-1], stem:["LHS" = (1-x)^-1].
When stem:[m=1], stem:[((m+k-1),(m-1)) = ((k),(0)) = 1].

So the stem:["RHS" = sum _(k>=0) x^k = (1-x)^-1] as required.

1H: Assume stem:[m>=1] and that stem:[(1-x)^-m = sum _(k>=0) ((m+x-1_,(m-1))x^k].

Consider stem:[m+1]:

[stem]
++++
(1-x)^(-m+1) = (1-x)^-1 (1-x)^-m

= (sum _(k>=0) x^k) (sum _(k>=0) ((m+k-1),(m-1)) x^k)

= (sum _(k>=0) (sum _(i>=0) ^k ((m+i-1),(m-1))) x^k
++++

By 1H def of multipliation of fps.

We proved last week that stem:[sum _(j=0) ^k ((m+j-1),(m-1) = ((m+k),(m))].
So stem:[(1-x)^(-(m+1)) = sum _(k>=0) ((m+k),(m)) x^k] as required.

So by induction, the statement holds. stem:[square]

.Theorem (Finite Geometric Series)
****
Let stem:[k] be a nonnegative integer. Then

[stem]
++++
1+x+x^2+x^3 + ... + x^k = (1-x^(k+1))/(1-x)
++++
****

Proof: stem:[(1-x)(1+x+x^2+...+x^k) = 1+x-x+x^2-x^2+...- x^k+1 = 1-x^(k+1)]

So remember: when finding coefficients for fps, here's your toolbox:

* stem:[(1-x)^-m = sum _(k>=0) ((m+k-1),(m-1))x^k]
* stem:[(1-x)^-1 = sum _(k>=0) x^k] 
* Finite Geometric Series (above)
* Binomial Theorem



== Sum and Product Lemmas

.Sum Lemma
****
If stem:[S = AuuB] where stem:[AnnB = O/],
[stem]
++++
Phi_S(x) = Phi_A(x) + Phi_B(x).
++++
****

.Product Lemma
****
If stem:[A_1, A_2] are sets with weight functions stem:[w_1, w_1],
and stem:[S = A_1xxA_2] has stem:[w((a_1, a_2)) = w_1(a_1)w_2(a_2)],
[stem]
++++
Phi_S(x) = Phi_(A_1)(x)Phi_(A_2)(x)
++++
****

Proofs are pretty simple.


== How to solve an enumeration problem


. Describe a set stem:[S] and a weight function stem:[w: S -> ZZ_(>=0)}
such that the answer to the problem is "the number of elements of stem:[S]
with weight stem:[n]".

. Find the generating series stem:[Phi_S(x)] for stem:[S] with respect to
stem:[w].

. Find the coefficient stem:[[x^n\]Phi_S(x)]. This is the answer.

====
Let stem:[n] and stem:[k] be nonnegative integers, How many nonnegative integer
solutions are there for stem:[t_1 + t_2 + ... + t_k = n]?

Choose stem:[S = ZZ_(>=0) xx  ZZ_(>=0) xx  ZZ_(>=0) xx ... =  ZZ_(>=0)^k].
Choose stem:[w(t_1, t_2, ..., t_k) = t_1 + ... + t_k].

We know stem:[Phi_ZZ_(>=0) = 1 + x + x^2 + ... = 1/(1-x)] with respect to
stem:[w_0(sigma) = sigma]. We can use the product lemma to get

[stem]
++++
Phi_x(s) = (Phi_ZZ_(>=0)(x))^k = (1-x)^-k.
++++

Now,

[stem]
++++
[x^n] (1-x)^-k = ((k+n-1),(k-1)).
++++

This solves our donut problem from the beginning.
We want stem:[t_c + t_m + t_l + t_p = 12] -- 12 donuts
from 4 types. And the answer is stem:[((15),(3)) = 455].

====

====
Okay, same thing but there are only 3 cocolate and 5 maple donuts. So we start with

[stem]
++++
S = {0,1,2,3} xx {0,2,3,4,5} xx ZZ_(>=0) xx ZZ_(>=0}.

"Recall " Phi_{0,1,..., n}(x) = 1+x+x^2+...+x^n = (1-x^(n+1))/(1-x).
++++

So we get

[stem]
++++
Phi_S(x) = ((1-x^4)/(1-x)) ((1-x^6)/(1-x)) (1/(1-x))^2 = (1-x^4-x^6+x^10)/(1-x)^4
++++

by the product lemma, and we end up with stem:[[x^12\] Phi_S(x) = 216] if we work
it out.
====

== Compositions of an Integer

A *composition* of an integer stem:[n] with stem:[k] parts is a stem:[k]-tuple
stem:[(t_1, t_2, ..., t_k)] of _positive_ integers such that stem:[t_1 + t_2 + ... + t_k = n].

How many stem:[k]-part compositions of stem:[k] are there?

Taking stem:[S] as stem:[ZZ_(>=1)^k], we have stem:[Phi_S(x) = (x/(1-x))^k].
Expanding, we get stem:[((n-1),(k-1))].

.A more complex composition problem
****
How many compositions of stem:[n] in stem:[k] parts are there where the stem:[i]th part
stem:[k_i] is at least stem:[2i]?

Solve in the same way.
****


== Binary Strings

A *binary string* is some stem:[k in {0,1}^n], such as stem:[(1,0,0,1,1,0)], which we write as
stem:[100110].

A typical question might be "how many binary strings of length stem:[n] are there, such that
no substring stem:[11] appears?"

We'll mostly be using the length of the string as the weight function.

====
If stem:[S =] the set of all binary strings, stem:[w(sigma)] is the length of stem:[sigma].

Then the number of elements of stem:[S] of weight stem:[n] is stem:[2^n]. This gives us

[stem]
++++
Phi_S(x) = 1+2x+4x^2+8x^3+... = 1/(1-2x)
++++
====

Let stem:[A] and stem:[B] be sets of binary strings. For stem:[a in A] and stem:[b in B],
of lengths stem:[k] and stem:[l] respectively, the string stem:[ab] is the *concatenation*
of stem:[a] and stem:[b], and it has length stem:[k+l]. The *concatenation set*
stem:[AB = {ab: a in a, b in B}].

For instance, if stem:[A = {01, 00, 001}] and stem:[B = 1, 110}, then
stem:[AB = {011, 01110, 001, 00110, 0011, 001110}. Note the obvious bijection;
it is not always present in concatenation sets.

An example without a bijection is stem:[A = {011, 01}] and stem:[B = {0, 10}].
This gives us a set of only three elements, stem:[AB = {0110, 01110, 010}].
Our bijection has two elements stem:[(011, 0}] and stem:[(01, 10)], which correspond
to the same element of the concatenation set.

A concatenation set stem:[AB] is considered *unambiguous* if, for every stem:[sigma in AB],
there exists a _unique_ pair stem:[a in A, " " b in B] such that stem:[sigma = ab].
You'll learn to love unambiguous sets, because ambiguous ones apparently suck.

For a set stem:[A] of binary strings, we define another set
stem:[A** = {epsilon}uuAuuA^2uuA^3uu...].
We say stem:[A**] is unambiguous if for each stem:[sigma in A**], there exists a unique 
stem:[k]-tuple stem:[(a_1,a_2,...,a_k) in A^k] such that stem:[sigma = a_1a_2...a_k].

====
Take the set stem:[A={00, 101, 11}].
Show stem:[A**] is unambiguous. We use induction on the length of
stem:[sigma in A**].

Iff stem:[sigma] has length stem:[>0], and any shorter string in stem:[A**]
has a unique representation:

Consider stem:[sigma = a_1a_2...a_k] where stem:[a_i in A].
If the first digit of stem:[sigma] is stem:[0], then stem:[a_1 = 00].
If it is stem:[1], and is followed by a stem:[0], then stem:[a_1 = 101].
If it is stem:[1], and is followed by a stem:[1], then stem:[a_1 = 11].

Then stem:[a_1] is unambiguous.
We then know inductively that stem:[a_2...a_k] is unique.

stem:[square]

NOTE: If we try this proof with an ambiguous set, like stem:[{011, 01, 10, 110}],
we won't be able to say "if that stem:[1] is followed by a stem:[0]" because we're
not guaranteed to not be bleeding into the next stem:[a_n] like we are in the above
problem.
====

== Product Lemma for Binary Strings

Given sets of binary strings stem:[A] and stem:[B], suppose stem:[AB] is unambiguous.
Then stem:[Phi_(AB)(x) = Phi_A(x) Phi_B(x)], where the weight function is length in all
cases. Proof is same as the other Product Lemma.

== Star Lemma

Let stem:[A] be a set of binary strings. Suppose stem:[A**] is unambiguous. Then

[stem]
++++
Phi_(A**)(x) = 1/(1-Phi_A(x))
++++

where weight is length.

Proof: stem:[A** = {epsilon}uuAuuA AuuA A Auu...].
Since stem:[A**] is unambiguous, stem:[Phi_(A^k) = (Phi_A(x))^k] by PL
and stem:[Phi_(A**) = sum _(k>=0) (Phi_(A^k)(x))^k]. Therefore
stem:[Phi_(A**)(x) = 1/(1-Phi_A(x))].


[stem]
++++
Phi_({1}**) (x) = 1/(1-Phi_({1}) (x))
++++

This is trivial.

The set of all binary strings is stem:[{1, 0}**]. Note that
this means stem:[{1, 0}**] is unambiguous. Then we know the
generating series for stem:[Phi_({0, 1}**) = 1/(1-2x)], by the
star lemma.

== 0-Decomposition

[stem]
++++
{0, 1}** = {1}**({0}{1}**)**
++++

and the RHS is unambiguous.

.Proof
****
Let stem:[sigma in {0, 1]**]. Then stem:[sigma] has stem:[k >= 0] zeroes.
Then stem:[sigma] has a unique expression as stem:[sigma = a_0 0a_1 0a_2 ... a_(k-1) 0 a_k],
where each stem:[a] is a (possibly empty) string of stem:[1]s.

Then stem:[a_0 in {1}**], and stem:[0a_i in {0}{1}**], for every stem:[1 <= i <= k]. stem:[square]
****

====
How many binary strings of length stem:[n] are there that do not contain the substring stem:[11]?

We know stem:[{0, 1}** = {1}** ({0}{1**)**]. Our set stem:[S = {epsilon, 1} ({0}{epsilon, 1})**]
is a restriction of the stem:[0]-Decomposition, hence is unambiguous (weight is length).

[stem]
++++
Phi_({epsilon, 1}) (x) = 1+x

Phi_({0}) (x) = x
++++

Thus

[stem]
++++
[Phi_S (x) = (1+x) 1/(1-x(1+x))]

= (1+x)/(1-x-x^2)
++++

 by PL, *-L. The standard form to write a generating series as a *rational expression*
is as a quotient of polynomials.
====

====
If we wanted to solve for the generating series
of all binary strings not containing stem:[000],
we'd have to use the stem:[1]-decomposition instead
of the stem:[0] decomposition.

stem:[S = {epsilon, 0, 00} ({1} {epsilon, 0, 00})**
====

== Block Decomposition

A *block* in a binary string is a nonempty maximal substring of all stem:[0]s
or all stem:[1]s. This gives us the *block composition theorem*,

[stem]
++++
{0, 1}** = {1}**({0}{0}**{1}{1}**){0}**,
++++

where RHS is unambiguous. Proof is pretty trivial.

====
Find the generating series for all the binary strings where
all blocks of zero have even length, and all block of one
have odd length.

[stem]
++++
{0, 1}** = {1}**({0}{0}**{1}{1}**){0}**

S = ({epsilon}uu{1}{11}**)({00}{00}**{1}{11}**)**{00}**
++++

This definition of stem:[S] is unambiguous, since it's a restriction
of the block decomposition. As usual with binary strings, stem:[w(sigma)=]
length.

[stem]
++++
Phi({1}{11}**)(x) = x + x^3 + x^5 + ... = x(1+x^2 + x^4 + ...) = x/(1-x^2)

Phi({00}{00}**)(x) = x^2 + x^4 + x^6 + ... = x^2/(1-x^2)
++++

Then by the product lemma and star lemma,

[stem]
++++
Phi_S(x) = (1+x)/(1-x^2) * 1/(1-(x^2/(1-x^2))(x/(1-x^2))) * (1/(10-x^2))

= (1-x^2+x)/(1-x^2) * (1-x^2)^2/((1-x^2)^2 - x^3) * 1/(1-x^2)

= (1+x-x^2)/(1-2x^2-x^3 + x^4)
++++
====

====
Find the generating series for the set of binary strings
where each even block of zeroes is followed by a block
of two ones.

[stem]
++++
S = {1}*({00}{00}**{11} uu {0}{00}**{1}{1}**{0}{00}**
++++

This is unambiguous, since it's a restriction of the block decomposition.

[stem]
++++
Phi_({00}{00}**)(x) = x^2/(1-x^2)

Phi_({00}{00}**{11}) (x) = x^2/(1-x^2) * x^2

Phi_({0}{00}**{1}{1}**) (x) = x/(1-x^2) * x/(1-x)

Phi_({epsilon} uu {0}{00}**) (x) = 1+x/(1-x^2)

Phi_S(x) = 1/(1-x)* 1/(1-(x^4/(1-x^2) + x^2/((1-x)(1-x^2)))) * (1+x/(1-x^2))

= (1+x-x^2)/(1-x-2x^2+x^3-x^4+x^5)
++++
====

====
Find the generating series for the set of binary strings
which do not contain the substring stem:[11100].

[stem]
++++
{0, 1}** = {1}**({0}{0}**{1}{1}**){0}**

S = {0}** ({1}{1}** {0}{0}**  \\ {111}{1}** {00}{0}**)** {1}**
++++

Restriction of block decomposition, so it's unambiguous.

[stem]
++++
Phi_({1}{1}**{0}{0}**) (x) = Phi_M(x) + Phi_A(x)

Phi_M (x) = (x/(1-x))^2 - (x^2/(1-x)) (x^2/(1-x)) " by PL"

Phi_S(x) = (1/(1-x)) (1/(1-Phi_M(x))) (1/(1-x)) = EX " by PL, *L"

= 1/(1-2x+x^5)
++++
====

====
Find the generating series with respect to length for
binary strings without the substring stem:[010].

[stem]
++++
{0, 1}** = {1}**({0}{1}**)** " (zero decomp)"

S_0 = {1}**({0}({epsilon}uu{11}{1}**)**
++++

But this doesn't quite cover every case.
Consider that none of these strings can ever end in stem:[01].
So we switch it to 

[stem]
++++
S = {1}**({0}({epsilon}uu{11}{1}**))**({epsilon, 01})
++++

This expression is unambiguous, because stem:[S_0] is unambiguous,
and no element of stem:[S_0] can end in stem:[01] (so we know any
element ending with stem:[01] reduces to an element of stem:[S_0]
without the terminal stem:[01]).

Skipping a few steps, we end up with

[stem]
++++
Phi_S(x) = 1/(1-x) (1/(1-x(1+x^2/(1-x))))(1+x^2)

= (1+x^2)/(1 - 2x + x^2 - x^3
++++
====

== Recursive Decomposition

We express a set of binary strings in terms of itself.

====
Example: stem:[S = {0, 1}**]. Every string stem:[sigma in S] satisfies
exactly one of the following:

* stem:[sigma = epsilon]
* stem:[sigma] starts with a stem:[1] and continues with an element of stem:[S]
* stem:[sigma] starts with a stem:[0] and continues with an element of stem:[S]

So stem:[S = {epsilon} uu {1}S uu {0}S].

By SL, PL,

[stem]
++++
Phi_S(x) = 1+x Phi_S(x) + x Phi_S(x)
++++

====

====

stem:[S =] the set of all binary strings not containing the substring
stem:[00].

Then every stem:[sigma in S] satisfies one of:

* stem:[sigma in epsilon]
* stem:[sigma = 0]
* stem:[sigma] starts with 1 and continues with an element of stem:[S]
* stem:[sigma] starts with stem:[01] and continues with an element of stem:[S]

Then stem:[S = {epsilon} uu {0} uu {1}S uu {01}S], which is unambiguous. Then

[stem]
++++
Phi_S(x) = 1+x+x Phi_S(x) + x^2 Phi_S(x)

Phi_S(x) = (1+x)/(1-x-x^2)
++++
====

====
Let stem:[L] be the set of bunary strings with no substring stem:[11010].

Let stem:[M] be the set of binary strings with exactly one substring
stem:[11010], occuring at the end.

Claim:

. stem:[{epsilon} uu L{0, 1} = LuuM]
. stem:[L{11010} = M]

and these expressions are unambiguous.

Proof: Cleary stem:[epsilon sub L sub LuuM]. Also, stem:[L{0, 1} sub LuuM],
since adding one digit to the end of stem:[sigma in L] gives an element
which either still has no substring stem:[11010], or which has one right at
the end.

Suppose stem:[sigma in LuuM]. If stem:[sigma in L] and stem:[sigma != epsilon],
then we can remove its last digit and get another string in stem:[L].

If stem:[sigma in M], then removing its last digit ruins the only substring stem:[11010]
in stem:[sigma], hence hte result is in stem:[L]. Hence the first claim holds.

Now, suppose stem:[sigma in L{11010}]; say stem:[sigma = sigma_1 11010]. There's
a risk that stem:[sigma] contains some instance stem:[11010] other than the one
right at the end -- a chance that the first few characters in stem:[11010] combine
with the last few characters of stem:[sigma] to form another stem:[11010].

It turns out that this isn't an issue, since no strict substring of stem:[11010] starting
at the beginning is equal to a substring of stem:[11010] ending at the end. There's nowhere
else that that stem:[11] can go. So we're safe on this count. The prof actually wrote
out all the cases of "the first stem:[n] characters stem:[!=] the last stem:[n] characters,"
so it seems like this is the recommended way to do that check.

Then, by SL and PL, we have

[stem]
++++
1+2xPhi_L(x) = Phi_L(x) + Phi_(x)

x^5 Phi_L(x) = Phi_M(x)
++++

which leads to

[stem]
++++
Phi_L(x) = 1/(1-2x+x^5)
++++
====

== Finding Coefficient in Rational Expressions

Reall the GS for binary strings w/ no substring stem:[11] is

[stem]
++++
Phi_S(x) = (1+x)/(1-x-x^2)
++++

We want to find stem:[a_n = [x^n\] Phi_S(x)]. Recall we can get
a recurrence relation for stem:[{a_n}].

[stem]
++++
sum_(n>=0) a_nx^n = (1+x)/(1-x-x^2)

sum_(n>=0) a_nx^n - sum_(n>=0) a_nx^(n+1) - sum_(n>=0) a_nx^(n+2) = 1+x
    
sum_(n>=0) a_nx^n - sum_(n>=1) a_(n-1)x^n - sum_(n>=2) a_(n-2)x^n = 1+x
++++

The coefficient of stem:[x^0] tells us stem:[a_0 = 1], stem:[a_1 - a_0 = 1
:. a_1 = 2], stem:[a_n - a_(n-1) - a_(n-2) = 0]. 

So we have a recurrence relation:

[stem]
++++
{(a_0 = 1),(a_1 = 2),(a_n = a_(n-1) + a_(n-2) AA n >= 2):}
++++

Can we find a closed-form expression for this? Sure!

Suppose stem:[alpha = (1+sqrt x)/2] and stem:[beta = (1-sqrt x)/2].

Then stem:[(1-alpha x)(1-beta x) = 1-x-x^2)]. And so

[stem]
++++
Phi_S(x) = (1+x)/((1-alpha x)(1-beta x))

= (1/2 + 3/(2 sqrt 5))/(1-alpha x) (1/2 - 3/(2 sqrt 5))/(1 - beta x)
++++

and we can plug in whatever number we want to get the coefficient.

[stem]
++++
[x^n]Phi_S(x) = (1/2 + 3/(2 sqrt 5) " " [x^n] (sum _(n>=0) alpha^nx^n)
+ (1/2 - 3/(2 sqrt 5)) " " [x^n] (sum _(n>=0) beta^nx^n)
++++

This looks _absolutely nuts,_ but it actually provides integer solutions
at integer values of stem:[n]. _YEAH, I KNOW._

stem:[alpha] and stem:[beta] are the roots of the *reciprocal polynomial*
to stem:[1-x-x^2], which is stem:[y^2 = y-1].

Since stem:[y^2 = y-1 = (y-alpha)(y-beta)], we can plug in stem:[y = 1/x] and
get stem:[1-x-x^2 = (1-alpha x)(1- beta x)]. We will return to this
later, with more rigour.

.Partial Fractions
****
Let stem:[g(x)] be a polynomial with constant coefficients. Let stem:[Theta_1]
through stem:[Theta_k] be distinct complex nmbers and stem:[m_1] through stem:[m_k]
be positive integers such that:

[stem]
++++
g(x) = (1-Theta_1x)^(m_1) ... (1-Theta_kx)^(m_k).
++++

Let stem:[f(x)] be a polynomial with degree stem:[< "deg"(g(x))].
Then there exist polinomials stem:[q_1(x) ... q_k(x)] with
stem:["deg"(q_1(x)) < m_i] for each stem:[i] such that

[stem]
++++
(f(x))/(g(x)) = (q_1(x))/(1-Theta_1x)^(m_1) + ... + (q_k(x))/(1-Theta_kx)^(m_k).
++++

Proof in notes; really more algebraic than combinatoric.
****

====
Find stem:[A], stem:[B], and stem:[C] for this polynomial.

[stem]
++++
(1-6x+18x^2)/((1-3x)^2(1-2x)) = (Ax+B)/(1-3x)^2 + C/(1-2x)

1-6x+18x^2 = (Ax+B)(1-2x)+C(1-3x)^2

x=1/3 => 1 = 1+2-2 = (A/3+B)1/3 => 9 = A+3B

x=1/2 => 5/2 = C/4 => C = 10

x=0 => 1=B+C => B = -4 => A= 36
++++
====

== Recurrence Relations

A (homogenous linear) *recurrence relation* for a sequence
stem:[{a_n}_(n>=0}] is an expression of the form

[stem]
++++
a_n + q_1a_(n-1) + q_2a_(n-2) + ... + q_ka_(n-k) = 0
++++

(where stem:[q_1] through stem:[q_k] are constants)
where the *initial conditions* stem:[a_0] through stem:[a_(k-1)]
are given.

We saw that the sequence of coefficients stem:[{a_n}_(n>=0)] of
a rational expression stem:[(f(x))/(g(x))] (where stem:[f(x)] and
stem:[g(x)] are polynomials, stem:[g(x)] has constant coefficients)
has a HLRR defining it. 

We also saw that the sequence stem:[{a_n}_(n>=0}] can be found
explicitly using partial fractions.

Can we use these facts to solve recurrence relations in general?
Yeah.

****
Fix stem:[k>=1]. Let stem:[{c_n}_(n>=0)] be a sequence such that for all
stem:[n>=k]

[stem]
++++
AA n>=k " " c_n + q_1c_(n-1) + q_2c_(n-2) + ... + q_kc_(n-k) = 0
++++

Let stem:[g(x) = 1 + q_1x + q_2x^2 + ... + q_kx^k]. Then
there exists a polynomial stem:[f(x)] with stem:["deg"(f(x))<k]
such that

[stem]
++++
C(x) = sum_(n>=0) c_nx^n = (f(x))/(g(x))
++++

Proof: Consider stem:[g(x)C(x)]. We want to show that this
is a polynomial of degree stem:[<k], i.e. show

[stem]
++++
AA n>=k " " [x^n]g(x)C(x) = 0

[x^n]g(x)C(x) = [x^n](1+q_1x+q_2x^2 + ... + q_kx^k
sum_(n>=0) c_nx^n

= [x^n](sum_(n>=0) c_nx^n + q_1 sum_(n>=0) c_(n-1)x^n
+ q_2 sum_(n>=0) c_(n-2)x^n + ... + q_k sum_(n>=0) c_(n-k)x^n

= c_n + q_1c_(n-1) + q_2c_(n-2) + ... + q_kc_(n-k) = 0
" for all " n>=k

square
++++
****

Now we can use partial fractions to get the following theorem:

****
For each recurrence relation 
stem:[a_n + q_1a_(n-1) + q_2a_(n-2) + ... + q_ka_(n-k) = 0]
where stem:[a_0] through stem:[a_(k-1)] are given,
the *characteristic polynomial* of stem:[{a_n}_(n>=0)] is

[stem]
++++
c(y) = y^k + q_1y^(k-1) + ... + q_(k-1)y + q_k
++++

Let stem:[beta_1 ... beta_j] be the distinct roots of
the characteristic polinomial c(y), with multiplicities
stem:[m_1 ... m_j] respectively, i.e.

[stem]
++++
c(y) = (y-beta_1)^(m_1) + (y-beta_2)^(m_2) + ... + (y-beta_j)^(m_j)
++++

Then the solution to the recurrence for stem:[{a_n}_(n>=0)] is 
stem:[a_n = P_1(n)beta_1^n + P_2(n)beta_2^n +  P_j(n)beta_j^n],
where stem:[P_i(n)] is a polynomial in stem:[n] of degree stem:[<= m_i-1],
for stem:[1<=i<=j].

The coefficients of the polynomials stem:[P_i(n)] are chosen to fit the initial
conditions stem:[a_0 ... a_k-1].

For example, for the sequence stem:[{a_n}_(n>=0)] defined by

[stem]
++++
{(a_n = 4a_(n-1) - 5a_(n-2)+2a_(n-3)),
(a_0 = 4),(a_1 = 9),(a_2=17,):}
++++

write stem:[a_n-4a_(n-1)+5a_(n-2)-2a_(n-3) = 0].
The char. polyn is stem:[c(y) = y^3 - 4y^2 + 5y - 2].
Find the roots of stem:[c(y)]; observe that stem:[1]
is a root, then do polyn division with it.

You end up with stem:[c(y) = (y-1)(y^2-3y+2) = (y-1)^2(y-2)].

The solution is stem:[a_n = (A+B_n)1^n + C2^n] with constant stem:[A, B, C].

We can then solve this algebraically from the initial conditions of
stem:[a_0, a_1, a_2].

****

====
[stem]
++++
b_n = 4(2)^n - 3^n + (4n-1)(-1)^n
++++

Find a recurrence relation with initial conditions that define stem:[b_n]
for all stem:[n>=0].

Start off by finding a polynomial whose roots are stem:[2, 3, -1, -1].
We use stem:[(y-2)(y-3)(y+1)(y+1) = y^4-3y^3-3y^2+7y+6].

If this is the characteristic polynomial, then the recurrence for stem:[b_n]
should be stem:[b_n - 3b_(n-1) + 7b_(n-2) +6b_(n-4) = 0] for stem:[n>>=4].

We can sub stem:[0, 1, 2, 3] into the closed-form formula in order to 
get values for them. We end up with

|===
|stem:[b_0] |stem:[2]
|stem:[b_1] |stem:[2]
|stem:[b_2] |stem:[14]
|stem:[b_3] |stem:[-6]
|===
====

== Graph Theory

A *graph* stem:[G] consists of a finite set stem:[V] of *vertices*
and a set stem:[E] of *edges*, where each edge in stem:[E] is a subset
of stem:[V] of size stem:[2].

For example, stem:[V = {a, b, c, d}] and
stem:[E = {{a, b}, {a, c}, {c, d}, {b, d}}].

We usually denote an edge stem:[{a, b}] as stem:[ab], because we're lazy.

Graphs don't have loops stem:[{a, a}], because these aren't sets,
they're multi-sets.
They also don't have more than one of the same edge, as in
stem:[{{a, b}, {a, b}}], for the same reason.

A vertex stem:[v] is said to be *adjacent* to a vertex stem:[w] if
stem:[vw in E]. We also say stem:[v] and stem:[w] are neighbours.
We say the edge stem:[vw] joins stem:[v] and stem:[w].
The number of neighbours a vertex has is its degree, written stem:["deg"(v)].
A vertex of degree zero is an isolated vertex.
A vertex stem:[v] is incident to each edge stem:[vw] and stem:[v] is an endpoint
of stem:[vw].

Two graphs are isomorphic if you could relabel the nodes and then they'd be equal.
Meaning there's a function stem:[f: V(A) -> V(B)] called an isomorphism, satisfying:

* stem:[f] is a bijection
* stem:[f(a)f(b)] is an edge of stem:[B] iff stem:[ab] is an edge of stem:[A].

[graphviz]
....
graph {
    a -- b
}
....
